name: Angular Build & Deploy to Firebase

on:
  push:
    branches:
      - deployment  # Change if you want another branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 5️⃣ Build Angular app
      - name: Build Angular app
        run: ng build --configuration production

      # 6️⃣ Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 7️⃣ Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --project magenet-734b3
