name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - deployment   # Change if your branch is 'deployment' or another name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > "${HOME}/firebase-key.json"
          firebase auth:login:ci || true
          firebase deploy --only hosting --project magenet-734b3 --token "$(firebase login:ci --no-localhost --token "$(cat ${HOME}/firebase-key.json)")"
