name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - deployment

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies (optional: remove if not building)
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build your project (optional: remove if not using a build step)
      - name: Build project
        run: npm run build

      # 5️⃣ Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 6️⃣ Save Firebase service account key to a file
      - name: Create Firebase key file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $GITHUB_WORKSPACE/firebase-key.json

      # 7️⃣ Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/firebase-key.json
        run: firebase deploy --only hosting --project magenet-734b3
